anchore/grype-db

- pkg/db/v1/model/vulnerability.go
- pkg/db/v1/model/vulnerability_metadata.go
- pkg/db/v1/reader/store.go
- pkg/db/v1/vulnerability.go
- pkg/db/v1/vulnerability_metadata.go
- pkg/db/v1/writer/store.go
- pkg/db/v1/writer/store_test.go
Adds the "Fixed In" version data for each vulnerability. This is different from the existing "Version Constraint" which is an arbitrary expression indicating the range(s) which the package is vulnerable.
Partially addresses https://github.com/anchore/grype/issues/144
> Add fixed-in-version to the vulnerability model

- pkg/db/schema_version.go
I made a PR so that I don't miss anything. I think the only thing needed is this one value.
> bump the schema to match the branch

- Makefile
- pkg/db/schema_version.go
The schema check is good for checking mismatched schema version relative to an expected value, but is not a good check for remembering to bump the version when the new schema version branch is made. This PR adds a the `GITHUB_BASE_REF`  as a value to test the schema version against --in this way when the PR is opened the check will be able to have enough information to make a validation against the known base branch, which matches the name of the schema.
> Add schema check to use GITHUB_BASE_REF

- pkg/db/v3/namespace.go
- pkg/db/v3/namespace_test.go
Adds the product ID to the MSRC namespace as a suffix.
(Related to https://github.com/anchore/grype-db-builder/issues/122)
> Update MSRC namespace to include product ID

- pkg/db/v3/namespace.go
- pkg/db/v3/namespace_test.go
Allow for a default guess at language namespaces, which is to try a github security advisory namespace
> Add default language namer

- .github/workflows/daily-db-publisher.yaml
- .github/workflows/release.yaml
- .github/workflows/update-grype-release.yml
- .github/workflows/validations.yaml
Use of `::set-output` in github actions is deprecated. This will effectively stop functioning on May 31st 2023. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This PR removes all uses of this function.
> Remove use of deprecated github actions funcion "set-output"

- .github/workflows/staging-db-publisher.yaml
- publish/src/publisher/utils/grype.py
Without the fixtures in LFS there is no way for the publish script to run acceptance tests on the built DB (example passing run https://github.com/anchore/grype-db/actions/runs/4387332143 )
> Include LFS in staging builds

- .github/workflows/daily-db-publisher.yaml
This swaps the daily DB workflow from the old repo (grype-db-builder) to this repo.
> Enable daily DB publisher workflow

- .github/workflows/daily-data-sync.yaml
Adds slack notification when grype-db data sync fails to aggregate all vunnel runs.
> Add slack notification for aggregation failures

- .github/scripts/aggregate-all-provider-cache.py
- .github/workflows/daily-data-sync.yaml
- Makefile
- cmd/grype-db/cli/cli.go
- cmd/grype-db/cli/commands/cache_status.go
- cmd/grype-db/cli/commands/list_providers.go
- cmd/grype-db/cli/commands/utils.go
- cmd/grype-db/cli/options/format.go
- pkg/provider/providers/vunnel/provider.go
Since the provider config generation from vunnel has been added, this ports over the daily data sync workflow to deriving the provider matrix from grype-db output (which runs vunnel internally), not a static grype-db config.
Additionally this PR:
- removes a very noisy slack notification in leu of a notification at the end of the data sync workflow
- fixes the makefile to always reference the publish config when running grype-db
- updates the aggregation script to use the make target
- allows for the daily db sync to continue on failure, using the previous day's cache for today's cache
> Add list-providers command

- publish/src/publisher/console.py
When we push an updated database out the listing file is updated with it, however, the TTL is set to 45 minutes so it takes a while for users to see the updated DB. This PR changes this behavior to bust the CDN cache within 5 minutes of updating the listing file.
> Update listing file CDN TTL to 5 minutes

- cmd/grype-db/cli/commands/build.go
- cmd/grype-db/cli/commands/pull.go
- cmd/grype-db/cli/options/vunnel.go
Today the `provider.vunnel.config` option is not exposed, this PR corrects this.
> Add vunnel config path to app config

- pkg/provider/providers/external/log_writer.go
- pkg/provider/providers/external/log_writer_test.go
Currently there won't be any logging surfaced from vunnel providers when grype-db isn't set to debug because all vunnel logs are being logged from go at the debug level.  Since the vunnel log level is configurable separately, this changes the default go log level output from vunnel to be Info and additionally attempts to parse the actual log level from the vunnel calls and log at the corresponding level from go.
> fix: surface vunnel logs with provider log level if possible

- cmd/grype-db/cli/commands/package.go
- cmd/grype-db/cli/options/package.go
- go.mod
- internal/tar/tar.go
- pkg/process/package.go
- publish/src/publisher/console.py
- publish/src/publisher/utils/constants.py
- publish/src/publisher/utils/listing.py
- publish/tests/utils/test_listing.py
Prototype for switching the distributed archives to `tar.zst` (over `tar.gz`) for better compression ratio without sacrificing decompression time (compressing one archive now takes ~3.5 minutes instead of ~15 seconds), compression time is essentially irrelevant (worth sacrificing) since this is run nightly.
| Method | Compression Ratio | Compression Time | Decompression Time (with grype) |
| --- | --- | --- | --- |
| gzip (today) | 6.83 | 15 seconds* | 3.8 seconds* |
| xz (-6) | 11.67* | 3.5 minutes | 30 seconds |
| zstd (-19) | 10.9 |  1.5 minutes | 4 seconds |
_* = best_
zstd appears to make the best trade offs for our use case (better compression ratio without sacrificing decompression time).
More background: https://linuxreviews.org/Comparison_of_Compression_Algorithms
Owed before …
> Swap compression method to zstd

- pkg/process/package.go
Follow up to #98 , we won't be able to pull the trigger on using zstd until all downstream users of this data pipeline are accounted for. For the meantime I'll leave the method in place with all validators so that all that would be needed is to revert this PR. This means that anyone who wishes to build tar.zst archives for their version of grype can still do so with this PR.
Needed before merging:
> Revert zstd as a default compression method

- .github/workflows/daily-db-publisher.yaml
- .github/workflows/staging-db-publisher.yaml
- .github/workflows/validations.yaml
- .gitignore
- .gitmodules
- config/grype-db-manager/include.d/validate.yaml
- data/yardstick/labels
- test/db/acceptance.sh
A few changes were made in this PR:
_More on the gitignore change..._
This is not valid:
```
/data
!/data/yardstick/labels
```
Tip of the hat to https://stackoverflow.com/questions/3203228/git-ignore-exception/72380673#72380673 on this one.
When running the production run yesterday there were no relative comparison differences so the labels were not used. However, today there happened to be differences, so the labels were attempted to be used, but the link was not checked in, so it was as if there were no labels. The gate (correctly) failed since there were too many matches that were unlabeled.
> Add yardstick labels symlink to gitignore

- pkg/process/v1/transformers/os/test-fixtures/amazon-multiple-kernel-advisories.json
- pkg/process/v1/transformers/os/transform.go
- pkg/process/v1/transformers/os/transform_test.go
- pkg/process/v2/transformers/os/test-fixtures/amazon-multiple-kernel-advisories.json
- pkg/process/v2/transformers/os/transform.go
- pkg/process/v2/transformers/os/transform_test.go
- pkg/process/v3/transformers/os/test-fixtures/amazon-multiple-kernel-advisories.json
- pkg/process/v3/transformers/os/transform.go
- pkg/process/v3/transformers/os/transform_test.go
- pkg/process/v4/transformers/os/test-fixtures/amazon-multiple-kernel-advisories.json
- pkg/process/v4/transformers/os/transform.go
- pkg/process/v4/transformers/os/transform_test.go
- pkg/process/v5/transformers/os/test-fixtures/amazon-multiple-kernel-advisories.json
- pkg/process/v5/transformers/os/test-fixtures/amzn.json
- pkg/process/v5/transformers/os/transform.go
- pkg/process/v5/transformers/os/transform_test.go
Fixes https://github.com/anchore/vunnel/issues/265
Before:
```
grype docker.io/anchore/test_images:vulnerabilities-amazonlinux-2-5c26ce9@sha256:cf742eca189b02902a0a7926ac3fbb423e799937bf4358b0d2acc6cc36ab82aa  | grep kernel-headers
✔ Parsed image                                                                                                                sha256:58073b915bd374c893f64b52d0bac8635006f6816e8b4c296c4e7d01dd11bdf2
✔ Cataloged packages              [285 packages]
✔ Scanned for vulnerabilities     [401 vulnerabilities]
├── 13 critical, 170 high, 197 medium, 21 low, 0 negligible
└── 360 fixed
kernel-headers                 4.14.275-207.503.amzn2       5.4.250-166.369.amzn2      rpm           ALASKERNEL-5.4-2023-050   High
kernel-headers                 4.14.275-207.503.amzn2 …
```
> fix: interpret constraints correctly for Amazon Linux Kernel advisories

- config/grype-db-manager/include.d/validate.yaml
The v1 and v2 schemas can only use grype versions that don't have epoch values on RPM package versions, which means that labels cannot be correctly applied. This means that any RHEL based image tends to easily cross the unlabeled matches threshold. I'll work on sunsetting the v1 and v2 schemas, but in the meantime to get DBs built again I've bumped this threshold.
> Workaround v1 and v2 schema differences

- manager/src/grype_db_manager/cli/db.py
- manager/src/grype_db_manager/s3utils.py
- manager/tests/unit/cli/test_db.py
- poetry.lock
- pyproject.toml
Previously we had been uploading DBs with the S3 CLI which had been inferring a mime type from any file it would upload and including the `ContentType` header. Once we moved to using boto3 this wasn't being done (we need to do it ourselves) -- this PR adds this functionality back.
> Upload DBs to s3 with ContentType header

- config/grype-db/publish-nightly.yaml
Vunnel v0.17.0 is broken and should not be used.  Pinning back to v0.16.0 until we can sort it out and cut a new release.
> chore: pin vunnel to v0.16.0

- config/grype-db/publish-nightly.yaml
Reverts anchore/grype-db#177 now that we have fixed the regression upstream in vunnel
> Revert "chore: pin vunnel to v0.16.0"

- manager/src/grype_db_manager/cli/db.py
- manager/src/grype_db_manager/grypedb.py
- manager/tests/cli/workflow-2-validate-db.sh
- manager/tests/cli/workflow-4-full-publish.sh
- manager/tests/unit/test_grypedb.py
Partially addresses #178
This is an addition to the validation of the DBs being published to ensure they have the minimum expected namespaces based on the current snapshot of namespaces that vunnel provides. 
This is not an ideal implementation, since it hard codes the list of namespaces for each supported schema (4-5, 1-3) and this is already captured for schemas 4-5 with https://github.com/anchore/vunnel/blob/main/tests/quality/config.yaml . The hard part about using this is we need to know the specific vunnel version used to be able to reference the correct yaml file (which, also unfortunately, means this would need to be an online operation). If the vunnel could output at least some of this information that would make a better long term path here.
This PR is not about the long term …
> Add basic namespace check on publishing DBs

- manager/tests/unit/cli/test_listing.py
test_create_listing behaves differently on listings that are older than 120 days. Change these tests to mock the file age calculation, rather than just making the files newer.
See https://github.com/anchore/grype-db/pull/209#issuecomment-1849940773
It would also be possible to change the datestamps in all the fixture JSON and recompute the expected checksums, but that work would have to be repeated every 4 months.
> chore: mock file age in python units

- pkg/process/v5/transformers/os/transform.go
- pkg/process/v5/transformers/os/transform_test.go
Always emit the `rpm-modularity` package qualifier for rpm rows as this is necessary to take advantage of the filtering by modularity in grype to prevent reporting of false-positive matches for packages of other modularities.
> fix: emit rpm-modularity qualifier for rpm rows

- .gitmodules
- manager/Makefile
- manager/src/grype_db_manager/cli/config.py
- manager/src/grype_db_manager/db/schema.py
- manager/tests/unit/cli/fixtures/config/full.yaml
- manager/tests/unit/cli/test_config.py
- manager/tests/unit/cli/test_listing.py
The schema mapping file is baked directly into `grype-db-manager`, which means if you want a subselection of the schema versions to be validated when updating a listing file you cannot. This change makes this file be configurable.
Additionally changes the submodule to be `https` not authed over `ssh`.
> Make schema mapping configurable

- pkg/process/package.go
When building multiple archives in the same day we need to make certain that we can order them from most recent to least recent. Today the "date" component in the archive represents the age of the data itself. This PR replaces the random trailer that guarantees uniqueness with the unix epoch of the time the DB is packaged. This helps to ensure that DBs can be well-ordered within the same day.
> Ensure that archived packages are well ordered

- manager/src/grype_db_manager/cli/config.py
- manager/src/grype_db_manager/cli/listing.py
- manager/src/grype_db_manager/db/listing.py
- manager/src/grype_db_manager/grypedb.py
- manager/tests/unit/cli/fixtures/config/full.yaml
- manager/tests/unit/cli/test_config.py
- manager/tests/unit/db/test_listing.py
This change allows for grype-db listing files to be replicated to multiple S3 locations via grype-db-manager application configuration:
```yaml
listing-file-name: listing.json
s3-path: grype/databases
s3-bucket: my-awesome-bucket.io
aws-region: us-west-2
download-url-prefix: https://my-awesome-bucket.io
listing_replicas:
- s3-path: v1/grype/databases
- s3-path: v2/grype/databases
s3-bucket: another-bucket.io
```
> Add listing replicas

- .vunnel.yaml
This only affects the OSS workflow in this repo to publish DBs (since this is not enabled by default)
> Enable NVD overrides for OSS workflow

- cmd/grype-db/cli/commands/cache_status.go
- cmd/grype-db/cli/commands/cache_status_test.go
This adds a flag to grype-db cache status to require that a certain number of rows be present in the database. By default, the value is zero, so that empty databases fail cache status. If empty databases are acceptable, `--min-rows -1` can be passed.
Previously, `grype-db cache status -p $SOME-PROVIDER` would exit zero in two situations where it probably shouldn't have:
1. Provider `$SOME-PROVIDER` is not present in the workspace _at all_. Hard to say a totally absent provider is valid.
2. The Provider `$SOME-PROVIDER` is present, but the results.db in their workspace has zero rows.
The intent of this PR is to guard against accidentally pushing workspace cache when the provider didn't find anything or restoring the provider cache failed.
> Fail cache status on empty results

- pkg/process/v1/writer.go
- pkg/process/v1/writer_test.go
- pkg/process/v2/writer.go
- pkg/process/v2/writer_test.go
- pkg/process/v3/writer.go
- pkg/process/v3/writer_test.go
- pkg/process/v4/writer.go
- pkg/process/v4/writer_test.go
- pkg/process/v5/writer.go
- pkg/process/v5/writer_test.go
Ensure that all severity values get normalized.  Previously normalization would be skipped for any records that weren't unknown, were from the NVD namespace, or were not based on CVE ids.  In those cases what should be skipped is defaulting to the NVD provider values when unknown, but not normalizing to a set enumeration of values
> fix: ensure normalization of all severity values

- manager/src/grype_db_manager/cli/listing.py
- manager/src/grype_db_manager/distribution.py
- manager/tests/cli/run.sh
- manager/tests/unit/cli/fixtures/listing/create-new-db/.grype-db-manager.yaml
Otherwise, the download-url-prefix http://example.com/ will result in listing files which are unparseable because they have // in the path which results in an incorrect S3 key.
> Remove trailing / in listing create

- cmd/grype-db/cli/commands/cache_backup.go
- cmd/grype-db/cli/commands/cache_backup_test.go
- cmd/grype-db/cli/commands/test-fixtures/test-root/test-provider/input/some-input-file.txt
- cmd/grype-db/cli/commands/test-fixtures/test-root/test-provider/metadata.json
- cmd/grype-db/cli/commands/test-fixtures/test-root/test-provider/results/results.db
- cmd/grype-db/cli/options/results.go
- pkg/provider/state.go
adding a --results-only switch to grype-db cache backup that ignores input directories
> feat: add --results-only switch to grype-db cache backup

- .github/scripts/curl-timing-info-template.txt
- .github/scripts/download-listing-and-db.sh
- .github/workflows/download-listing-and-db.yaml
A number of users have reported issues when attempting to download the database listing file and/or subsequent database, including:
* slowness
* 404 not found
* intermittent faillures
We are unable to reliably reproduce these problems, but occasionally see them ourselves. To attempt to get a bit more information about this, this PR adds a workflow that runs periodically so we can possibly see if certain times of day are particularly slower or more failure prone. Additionally, this checks IPv6 and IPv4 explicitly, as there may be some issues accessing these URLs with IPv6 when there is a cold cache of the database at the CDN.
> chore: add workflow to download latest db and listing periodically

- .github/scripts/download-listing-and-db.sh
This should help by highlighting slow downloads as failures in the github UI.
30 seconds to download the listing file and 120 seconds to download the database itself are the same as in Grype: https://github.com/anchore/grype/blob/57af1c34cb7db17824eac983cc6ae6945db47c88/cmd/grype/cli/options/database.go#L28-L29
Related to anchore/grype#1731
> chore: pass max time to download canary

- pkg/process/build.go
- pkg/process/v5/writer.go
adding the last successful run timestamp for all providers to the grype-db metadata.json file
> feat: add last successful run for each provider to the metadata

- README.md
- pkg/process/build.go
- pkg/process/v5/writer.go
grypedb should include last successful run date for each provider. grype db build will write a new file called `provider-metadata.json` that includes the last successful run date of each provider.
This was originally intended to be implemented in the existing `metadata.json` however we do have consumers that will depend on no new fields being added (https://github.com/anchore/grype/pull/1846 for more details).
Fixes: #255
> feat: grypedb should include last successful run date for each provider

- pkg/process/v5/transformers/os/test-fixtures/mariner-range.json
- pkg/process/v5/transformers/os/transform.go
- pkg/process/v5/transformers/os/transform_test.go
- pkg/provider/unmarshal/os_vulnerability.go
The Mariner distro feed will start including version ranges in the OVAL XML. Update models and grype-db transformer to be able to handle this in version 5.
This is the other half of https://github.com/anchore/vunnel/pull/585
> feat: enable os vulns to have version range

- manager/src/grype_db_manager/distribution.py
- manager/tests/unit/cli/test_listing.py
The listing file is large enough and frequently enough downloaded that we expect better performance with a smaller listing database file.
See anchore/grype#1731
> chore: shrink listing file to speed download times

- manager/tests/cli/workflow-3-update-listing.sh
- manager/tests/cli/workflow-4-full-publish.sh
Apparently "docker-compose" is no longer on PATH in GH actions runners. Switch to "docker compose".
Fixes #350
> fix: change workflow script from docker-compose to docker compose

- .github/workflows/daily-db-publisher-r2.yaml
- config/grype-db-manager/include.d/distribution-production-r2.yaml
- config/grype-db-manager/include.d/grype-db-local-build-r2.yaml
- config/grype-db-manager/publish-production-r2.yaml
- config/grype-db/publish-nightly-r2.yaml
This PR adds a secondary publishing workflow for publishing database and listing files to a secondary location.
> feat: publish database to secondary CloudFlare R2 bucket

- .github/workflows/copy-listing-from-r2.yaml
- .github/workflows/daily-db-publisher-r2.yaml
- .github/workflows/daily-db-publisher.yaml
- config/grype-db-manager/publish-production-r2.yaml
This adds a sync job from R2 to S3 to update the listing file so that all users are hitting the R2 bucket not S3. In the near future after a soak period we'll turn down the s3 workflow entirely.
> Sync listing.json from R2 to S3

- .grype-db-manager.yaml
- manager/src/grype_db_manager/cli/listing.py
- manager/src/grype_db_manager/db/listing.py
- poetry.lock
- pyproject.toml
Folks may want to craft and update a listing file directly out of an s3 bucket that is not publicly accessible yet, which means that validations should be skipped.
> Add ability to skip listing validations

- .github/workflows/daily-db-publisher-r2.yaml
This PR enables the R2 publishing to run daily.
> chore: enable R2 publishing schedule

- config/grype/acceptance.yaml
- manager/src/grype_db_manager/cli/db.py
- manager/src/grype_db_manager/db/validation.py
- pkg/process/v4/writer.go
- pkg/process/v5/writer.go
Otherwise, either the query for the ID will close because the database is closed already, or the checksum will be wrong because closing the database compacts it, which changes its checksum.
See anchore/grype#2076
> fix: query for ID before close but compute checksum after

- manager/src/grype_db_manager/cli/listing.py
- manager/src/grype_db_manager/db/listing.py
- manager/src/grype_db_manager/db/validation.py
- manager/tests/unit/cli/fixtures/listing/create-all-exists/.grype-db-manager.yaml
- manager/tests/unit/cli/fixtures/listing/create-all-exists/expected-listing.json
- manager/tests/unit/cli/fixtures/listing/create-all-exists/input-listing.json
- manager/tests/unit/cli/fixtures/listing/create-new-db/.grype-db-manager.yaml
- manager/tests/unit/cli/fixtures/listing/create-new-db/expected-listing.json
- manager/tests/unit/cli/fixtures/listing/create-new-db/input-listing.json
- manager/tests/unit/cli/test_listing.py
- manager/tests/unit/db/test_listing.py
Otherwise items created on the same day might end up in the wrong order.
Discovered during work on anchore/grype#2076
> fix: deterministically sort listing file

- pkg/process/v5/transformers/nvd/test-fixtures/CVE-2023-45283-platform-cpe-first.json
- pkg/process/v5/transformers/nvd/test-fixtures/CVE-2023-45283-platform-cpe-last.json
- pkg/process/v5/transformers/nvd/transform_test.go
- pkg/process/v5/transformers/nvd/unique_pkg.go
- pkg/process/v5/transformers/nvd/unique_pkg_test.go
Previously, this function would fall back to legacy behavior if it was looking at a configuration with a single platform CPE. However, the legacy behavior is incorrect for some orderings of the platform and application CPEs, so stop falling back.
> fix: use new platform logic even for only one platform

- config/grype-db-manager/include.d/validate.yaml
- manager/src/grype_db_manager/cli/config.py
- manager/src/grype_db_manager/cli/db.py
- manager/tests/unit/cli/fixtures/config/full.yaml
- manager/tests/unit/cli/test_config.py
- test/db/acceptance.sh
Versions of Grype using a schema before 5 will not recognize vulns in Azure Linux 3, so allow empty matches on the new result set for schemas 1 through 4.
Previously, db validate had an `--allow-empty-matches` flag that was sometimes passed, but because `grype-db-manager` is usually used in a mode where it validates every schema at once, it's simpler to wire up a config field that allows particular gates to have particular schemas that are allowed to be empty.
So this PR has 2 effects:
1. Change the prod config, so that for the new, small result set, when building and validating, allow old versions of grype to report empty matches on the new result set
2. Change the `db validate` CLI to use a configured value that specifies a list of schemas to allow empty matches on for a given set of …
> fix: allow empty matches on old schema versions

- go.mod
- go.sum
- pkg/process/package.go
- pkg/process/v1/writer.go
- pkg/process/v2/writer.go
- pkg/process/v3/writer.go
- pkg/process/v4/writer.go
- pkg/process/v5/writer.go
In preparation for v6, all distribution concerns are now a per-schema concern. In this case all v1-5 distribution concerns have been migrated to their own package.
> Use migrated grype DB distribution package

- RELEASE.md
Adds a short description of what makes up a grype-db release, also drops the background section (this is a procedure not a philosophy document)
> Update the release docs

- cmd/grype-db/cli/commands/build.go
- cmd/grype-db/cli/options/build.go
- pkg/process/build.go
- pkg/process/v5/processors.go
- pkg/process/v5/transformers/nvd/transform.go
- pkg/process/v5/transformers/nvd/transform_test.go
- pkg/process/v5/transformers/nvd/unique_pkg.go
- pkg/process/v5/transformers/nvd/unique_pkg_test.go
A new `build.include-cpe-parts` configuration has been added that will only allow including CPES from NVD entries with a specific part value. The CLI validates that only `a`, `h`, and `o` may be provided from the user. The default is to include only `a`.
```yaml
build:
include-cpe-parts: ["a", "o"]
```
> Add config for CPE part filtering

- cmd/grype-db/cli/commands/build.go
- cmd/grype-db/cli/options/build.go
- pkg/process/build.go
- pkg/process/v5/processors.go
- pkg/process/v5/transformers/nvd/transform.go
- pkg/process/v5/transformers/nvd/transform_test.go
Adds `build.infer-nvd-fix-versions` configuration around the new feature added in #112
> feat: configure nvd fix extraction

- .gitignore
- cmd/grype-db/cli/commands/cache_restore.go
- cmd/grype-db/cli/commands/cache_restore_test.go
- config/grype/acceptance.yaml
- internal/tarutil/file_entry.go
- internal/tarutil/file_entry_test.go
- internal/tarutil/reader_entry.go
- internal/tarutil/reader_entry_test.go
- manager/src/grype_db_manager/cli/db.py
- manager/src/grype_db_manager/db/validation.py
- manager/src/grype_db_manager/grypedb.py
- manager/tests/cli/.gitignore
- manager/tests/cli/workflow-2-validate-db.sh
Today we are backing up all of the vunnel cache providers, however, this does not support symlinks today --this PR adds support for this.
> Add symlink support for cache backup and restore

- manager/src/grype_db_manager/data/schema-info.json
- manager/tests/unit/db/test_schema.py
Per https://github.com/anchore/grype/issues/2075 we will no longer be building DBs for v1 & v2 schemas.
Closes https://github.com/anchore/grype/issues/2075
> Remove support for v1 & v2 schemas

- cmd/grype-db/cli/commands/build.go
- cmd/grype-db/cli/commands/build_test.go
This is an additional fix on top of #440 -- the original PR did not consider if NVD was the first provider on the list.
Example run:
```
[0002] DEBUG state validated for all providers
[0002] TRACE not considering data age for provider provider=nvd
[0002] DEBUG earliest data timestamp timestamp=2024-11-25 01:31:56.419535 +0000 +0000
[0002]  INFO building database build-directory=./build providers=[nvd alpine amazon chainguard debian github mariner oracle rhel sles ubuntu wolfi] schema=5
```
> Ignore NVD data age

- .vunnel.yaml
We're seeing that the NVD provider has ~250000 updates to CVEs waiting for us (we usually see no more then a few dozen to few hundred), but the API is intermittent and returning 503s a lot of the time. The best guess is that there's been a large data dump upstream and their incremental API is being over leveraged while everyone works through the backlog. We've seen some success locally with more retry attempts -- this PR adds such a configuration.
> Add more retry attempts for NVD provider

- .vunnel.yaml
Incorporates https://github.com/anchore/vunnel/pull/738 and adds more aggressive retries while also changing the request timeout to something less aggressive.
> Add request retry count for NVD

- cmd/grype-db/cli/commands/build.go
- cmd/grype-db/cli/commands/build_test.go
Because building the NVD provider is unreliable right now, normally grype-db won't consider the NVD time as the earliest timestamp. However, if NVD is the only provider, report it anyway, because otherwise single-provider grype-db builds always fail for NVD.
This is meant to fix errors like this one: https://github.com/anchore/vunnel/actions/runs/12112985815/job/33767270739#step:4:2298
> fix: use timestamp from only provider if only one provider

- DEVELOPING.md
- README.md
- cmd/grype-db/application/application.go
- cmd/grype-db/cli/commands/build.go
- go.mod
- go.sum
- internal/tarutil/writer.go
- pkg/process/package.go
- pkg/process/package_legacy.go
- pkg/provider/state.go
- pkg/provider/state_test.go
#436 covers the `build` subcommand, this PR covers plumbing v6 distribution behavior through the `package` command. The package command supports both v1-5 and v6 behaviors separately. 
The new v6 behavior:
- creates a `.tar.zstd` archive (thus related to https://github.com/anchore/grype-db/issues/367)
- does not embed any `metadata.json` or similar files into the archive
v1-5 behavior is unchanged.
Fixes #367
PR Stack:
1. https://github.com/anchore/grype-db/pull/436
> Enable packaging v6 DBs

- go.mod
- go.sum
- pkg/process/v6/transformers/os/transform.go
- pkg/process/v6/transformers/os/transform_test.go
Populates the OperatingSystem model for grype schema v6 with the original release ID (provided by vunnel providers).
> Add release ID to OS models

- config/grype-db/publish-nightly-r2.yaml
- config/grype-db/publish-nightly.yaml
Today we always run all vunnel providers, however, we may be adding more in the future that should not automatically be run by grype-db. For this reason we're pinning the specific providers that should be in the DB.
> Pin vunnel providers

- pkg/process/processors/github_processor.go
- pkg/process/processors/github_processor_test.go
- pkg/process/processors/match_exclusion_processor.go
- pkg/process/processors/match_exclusion_processor_test.go
- pkg/process/processors/msrc_processor.go
- pkg/process/processors/msrc_processor_test.go
- pkg/process/processors/nvd_processor.go
- pkg/process/processors/nvd_processor_test.go
- pkg/process/processors/os_processor.go
- pkg/process/processors/os_processor_test.go
- pkg/process/processors/version.go
- pkg/process/processors/version_test.go
We should allow processing all v1 schemas based off of the current supported values
https://github.com/anchore/vunnel/blob/85f3ba6bdd976babbea657a4aa78efe98e73e676/src/vunnel/schema.py#L7-L15
> Loosen vunnel schema version check

- .github/dependabot.yml
Fixes a typo in the dependabot config which was preventing automated updates to the composite bootstrap action definition.
> chore(ci): fix composite GitHub action path in dependabot config

- config/grype-db-manager/include.d/validate.yaml
When switching to alpine it was missed that there would be fewer than 10 packages (there should be 7). This drops the threshold to be a little lower than that to tolerate changes to vulnerability data.
> Fix listing.json validations threshold

- .github/workflows/release.yaml
While working on a new schema version it is possible to configure a new version that is published but quality gates are skipped -- including acceptance tests. This removes looking for acceptance test completions for schema versions that are supported but explicitly not running validations for.
> Skip release gate for unexpected acceptance tests

- .binny.yaml
- .github/actions/bootstrap/action.yaml
- .github/workflows/update-bootstrap-tools.yml
- go.mod
Update to building with go [1.24.x](https://tip.golang.org/doc/go1.24) so that the main module version gets set during go build
> feat: update to go 1.24.x

- pkg/process/v6/writer.go
- pkg/process/v6/writer_test.go
This mimics the v5 behavior of pulling NVD severities for records that have no severity or have an explicitly unknown severity.
> Add severity entries to missing vulnerability records (v6 only)

- pkg/process/v6/transformers/github/transform.go
There were a couple of issues and missing cases when transforming github security advisory namespaces to syft package types, this PR addresses those issues and uses syft pkg types directly to defend against potential value changes to these constants in the future.
> Explicitly use syft pkg types for v6 github transformer

- manager/src/grype_db_manager/db/latest.py
- manager/src/grype_db_manager/grype.py
- manager/src/grype_db_manager/grypedb.py
Schema versions expressed in v6 latest.json files now have a prefix `v`, this PR addresses this change.
> Account for v prefix on schema versions

- config/grype-db/publish-nightly-r2.yaml
- config/grype-db/publish-nightly.yaml
- pkg/process/build.go
This adds the [EPSS and KEV providers](https://github.com/anchore/vunnel/releases/tag/v0.31.0) to the nightly publish configs. This additionally changes how unprocessed records are logged. Today we log a schema reference for all records not processed, however, this results in a lot of logs that say the same thing in the case where a provider is not supported by a particular schema version (in this case schema v5 with EPSS and KEV providers). The presentation has been changed to show the number of unprocessed records for each schema and provider to the logs. Also, if no records were processed then the build process now will fail (`build` will have a return code of 1).
- I need to [rerun the data sync for today](https://github.com/anchore/grype-db/actions/runs/13525928541) based off of this …
> Enable EPSS and KEV vunnel providers

- manager/src/grype_db_manager/data/schema-info.json
- manager/tests/unit/db/test_schema.py
This PR pins grype for v5 to the latest version which supports it: v0.87.0
> fix: pin grype to v0.87.0 for v5

- .grype-v6.yaml
- config/grype-db-manager/include.d/validate.yaml
- manager/src/grype_db_manager/cli/db.py
- manager/src/grype_db_manager/data/schema-info.json
- manager/src/grype_db_manager/grype.py
- manager/tests/cli/.gitignore
- manager/tests/cli/.grype-v6.yaml
- manager/tests/cli/test_workflows.py
- pkg/process/default_schema_version.go
This will include v6 acceptance tests and other DB validations while removing the use of v6 feature flags used in development
> Enable v6 CI validations

- pkg/process/v6/transformers/nvd/transform.go
- pkg/process/v6/transformers/nvd/unique_pkg_test.go
Related to https://github.com/anchore/grype/issues/2365 , adds all CPEs from NVD to the DB, where previously we only added `a` types.
> Add hardware and operating system CPE parts

- pkg/process/v5/transformers/github/transform.go
- pkg/process/v5/transformers/github/transform_test.go
- pkg/process/v6/transformers/github/transform.go
- pkg/process/v6/transformers/github/transform_test.go
This effectively adds github-action advisories, however, they are disabled in v5 (as there is no version of grype that can effectively match on it).
> Fix processing of github-action entries

- cmd/grype-db/cli/commands/build.go
- cmd/grype-db/cli/options/build.go
- pkg/process/build.go
- pkg/process/v6/archive.go
Add the ability to build a fully hydrated db with `grype-db build`
> feat: allow db hydration during build

- config/grype-db/publish-nightly-r2.yaml
Reverts anchore/grype-db#581
This change causes db publish failures: https://github.com/anchore/grype-db/actions/runs/15401442015/job/43334751298
Attempts to roll forward quickly have proven that there are complexities to adding v6-only providers, since this has never been done before, see https://github.com/anchore/grype-db/pull/582
Therefore, revert until we figure this out, so that tonight's grype-db publishes normally.
(edit: force pushed to fix DCO - apparently GH UI "revert" button doesn't sign-off commits, or I didn't know how to tell it to.)
> Revert "feat: enable bitnami vuln data"

- pkg/process/v6/transformers/osv/transform.go
- pkg/process/v6/transformers/osv/transform_test.go
Previously, the CVSS vector would have the version prefix removed before serialization to the vulnerability blob, preventing Grype from parsing the vector into a severity to display. Instead retain the whole vector.
Fixes https://github.com/anchore/grype/issues/2725
> fix: include CVSS version in vector string

- pkg/process/v6/transformers/nvd/node.go
- pkg/process/v6/transformers/nvd/test-fixtures/CVE-2004-0377.json
- pkg/process/v6/transformers/nvd/transform_test.go
There is a bug in the v6 processing logic that can cause affected version ranges to be associated with the incorrect CPEs within a node configuration.
Fixes https://github.com/anchore/grype/issues/2807
> fix: incorrect associations between affected ranges and CPE

- .github/workflows/release.yaml
This is a follow up to the zizmore linter changes made -- we need to be able to push tags during releases, which requires persisting credentials
> Persist github auth for tag step during release

- .github/workflows/release.yaml
We should have a way to break-glass-in-case-of-emergency feature to release, skipping quality gates (which saves 45 mintues or so)
> Add release bypass

- cmd/grype-db/cli/commands/package.go
- cmd/grype-db/cli/options/package.go
- internal/tarutil/populate.go
- internal/tarutil/writer.go
- pkg/process/package.go
- pkg/process/package_legacy.go
- pkg/process/v6/archive.go
Allows for adding custom commands to compress the tar that is generated by grype-db.
```yaml
package:
compressor-commands:
gz: "gzip -c -9"
```
This allows us to try out more CLI tools for compression (such as pigz or zopfli)
> Add custom compressor commands to the config

- pkg/process/v6/transformers/nvd/test-fixtures/jvm-packages.json
- pkg/process/v6/transformers/nvd/transform.go
- pkg/process/v6/transformers/nvd/transform_test.go
When processing CPEs in the NVD provider, if a CPE seems to be for a JVM based on its package namme, set its version type to be "jvm" so that grype knows at match time to use special comparison logic for JVM versions.
> fix: recognize jvm versions at DB build time

- pkg/process/v6/transformers/github/test-fixtures/GHSA-2wgc-48g2-cj5w.json
- pkg/process/v6/transformers/github/test-fixtures/multiple-fixed-in-names.json
- pkg/process/v6/transformers/github/transform.go
- pkg/process/v6/transformers/github/transform_test.go
- pkg/process/v6/transformers/os/test-fixtures/alpine-3.9.json
- pkg/process/v6/transformers/os/test-fixtures/rhel-8.json
- pkg/process/v6/transformers/os/transform_test.go
- pkg/provider/unmarshal/github_advisory.go
Pairs with the changes in https://github.com/anchore/vunnel/pull/852 (also adds more tests around the OS transform changes introduced in https://github.com/anchore/grype-db/pull/629)
> Add fix available date to GHSA entries

- manager/src/grype_db_manager/grypedb.py
- manager/tests/unit/test_grypedb.py
Add opt-in environment variable `GRYPE_DB_EXECUTABLE_PATH` to allow using pre-built grype-db binaries instead of building from source. This enables running grype-db-manager in distroless containers or environments without Go toolchain installed.
- Added `GRYPE_DB_EXECUTABLE_PATH` environment variable support
- Uses cross-platform `shutil.which()` for executable validation
- Logs warning and falls back to source build if path is invalid
- No behavior change for existing users (opt-in only)
- Comprehensive test coverage for all scenarios
Useful for CI environments where grype-db binary is already available, eliminating the need for Go toolchain in container images. This **does** include the same checks, but skips the build / pull if the executable exists.
```bash
uv run pytest …
```
> Add GRYPE_DB_EXECUTABLE_PATH support to bypass Go build requirement
